import React, { Fragment } from 'react'
import Head from "next/head";
import { Menu, Transition} from "@headlessui/react"
import Link from "next/link"
import { useRouter } from "next/router"
import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import { doPushSignoutRequest } from "../../redux-saga/Action/UsrAction"

function classNames(...classes) {
  return classes.filter(Boolean).join(' ')
}

export default function Navbar(props) {
  const { children } = props
  const dispatch = useDispatch()
  const router = useRouter()
  const [user, setUser] = useState({})
  const { UserProfile } = useSelector(state => state.usrStated)

  const onSignout = () => {
    dispatch(doPushSignoutRequest())
    router.reload()
  }

  useEffect(() => {
    setUser(UserProfile)
  }, [])

  return (
    <div className="bg-wgite">
      <Head>
        <title>GitHub Jobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='bg-indigo-600'>
        <div className="fixed w-full bg-indigo-600 shadow-md lg:shadow-sm">
          <div className="flex justify-between items-center mx-auto px-4 py-4 sm:px-4 md:justify-start md:space-x-10 lg:px-12 bg-indigo-600">
            <div className="flex justify-start lg:w-0 lg:flex-1">
              <Link href="/">
                  <span className='text-white text-2xl font-semibold'>GitHub </span>
                  <span className='text-white text-2xl font-light'>Jobs</span>
              </Link>
            </div>

            <div className="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
              {
                user ?
                  <Menu as="div" className="ml-3 relative">
                      <div>
                          <Menu.Button className="flex">
                              <span className="sr-only">Open user menu</span>
                              <h4 className='text-white'>Hi, {user.username}</h4>
                          </Menu.Button>
                      </div>
                      <Transition
                          as={Fragment}
                          enter="transition ease-out duration-100"
                          enterFrom="transform opacity-0 scale-95"
                          enterhref="transform opacity-100 scale-100"
                          leave="transition ease-in duration-75"
                          leaveFrom="transform opacity-100 scale-100"
                          leavehref="transform opacity-0 scale-95"
                      >
                          <Menu.Items className="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none">
                              <Menu.Item>
                                  {({ active }) => (
                                      <Link
                                          href="/"
                                          onClick={onSignout}
                                          className={classNames(active ? 'bg-gray-100' : '', 'block px-4 py-2 text-sm text-gray-700')}
                                      >
                                          Sign out
                                      </Link>
                                  )}
                              </Menu.Item>
                          </Menu.Items>
                      </Transition>
                  </Menu> :
                  <>
                    <Link href="/" className="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900">
                        Sign in
                    </Link>
                  </>
              }
            </div>
          </div>
        </div>
      </header>

      <main>
        <div className="mb-6 pt-20 px-4 lg:px-12">
          {children}
        </div>
      </main>
    </div>
  )
}